<?php

use Illuminate\Database\Seeder;

class FontsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('fonts')->delete();
        
        $fonts = [
            ['id' => 1,       'family' => 'Bree_Serif',                  'category' => 'Serif',               'filename' => 'bree-serif-v8-latin-ext-regular.svg'],
            ['id' => 2,       'family' => 'Josefin_Slab',                'category' => 'Serif',               'filename' => 'josefin-slab-v9-latin-regular.svg'],
            ['id' => 3,       'family' => 'Marko_One',                   'category' => 'Serif',               'filename' => 'marko-one-v8-latin-regular.svg'],
            ['id' => 4,       'family' => 'Source_Serif_Pro',            'category' => 'Serif',               'filename' => 'source-serif-pro-v6-latin-ext-regular.svg'],
            ['id' => 5,       'family' => 'Ultra',                       'category' => 'Serif',               'filename' => 'ultra-v11-latin-regular.svg'],
            ['id' => 6,       'family' => 'Montaga',                     'category' => 'Serif',               'filename' => 'montaga-v6-latin-regular.svg'],
            ['id' => 7,       'family' => 'Bitter',                      'category' => 'Serif',               'filename' => 'bitter-v14-latin-ext-regular.svg'],
            ['id' => 8,       'family' => 'Vollkorn',                    'category' => 'Serif',               'filename' => 'vollkorn-v9-latin-ext-regular.svg'],
            ['id' => 9,       'family' => 'Holtwood_One_Sc',             'category' => 'Serif',               'filename' => 'holtwood-one-sc-v9-latin-regular.svg'],
            ['id' => 10,      'family' => 'Libre_Baskerville',           'category' => 'Serif',               'filename' => 'libre-baskerville-v6-latin-ext-regular.svg'],
            ['id' => 11,      'family' => 'Playfair_Display_Sc',         'category' => 'Serif',               'filename' => 'playfair-display-sc-v8-latin-ext-regular.svg'],
            ['id' => 12,      'family' => 'Coustard',                    'category' => 'Serif',               'filename' => 'coustard-v9-latin-regular.svg'],
            ['id' => 13,      'family' => 'Noto_Serif',                  'category' => 'Serif',               'filename' => 'noto-serif-v7-latin-ext-regular.svg'],
            ['id' => 14,      'family' => 'Volkhov',                     'category' => 'Serif',               'filename' => 'volkhov-v10-latin-regular.svg'],
            ['id' => 15,      'family' => 'Suez_One',                    'category' => 'Serif',               'filename' => 'suez-one-v3-latin-ext-regular.svg'],
            ['id' => 16,      'family' => 'Merriweather',                'category' => 'Serif',               'filename' => 'merriweather-v20-latin-ext-regular.svg'],
            ['id' => 17,      'family' => 'Martel',                      'category' => 'Serif',               'filename' => 'martel-v3-latin-ext-regular.svg'],
            ['id' => 18,      'family' => 'Alegreya',                    'category' => 'Serif',               'filename' => 'alegreya-v12-latin-ext-regular.svg'],
            ['id' => 19,      'family' => 'Slabo_27px',                  'category' => 'Serif',               'filename' => 'slabo-27px-v5-latin-ext-regular.svg'],
            ['id' => 20,      'family' => 'Old_Standard_Tt',             'category' => 'Serif',               'filename' => 'old-standard-tt-v11-latin-ext-regular.svg'],
            ['id' => 21,      'family' => 'Marcellus',                   'category' => 'Serif',               'filename' => 'marcellus-v6-latin-ext-regular.svg'],
            ['id' => 22,      'family' => 'Roboto_Slab',                 'category' => 'Serif',               'filename' => 'roboto-slab-v8-latin-ext-regular.svg'],
            ['id' => 23,      'family' => 'Rokkitt',                     'category' => 'Serif',               'filename' => 'rokkitt-v13-latin-ext-regular.svg'],
            ['id' => 24,      'family' => 'Kreon',                       'category' => 'Serif',               'filename' => 'kreon-v13-latin-regular.svg'],
            ['id' => 25,      'family' => 'Playfair_Display',            'category' => 'Serif',               'filename' => 'playfair-display-v14-latin-ext-regular.svg'],
            ['id' => 26,      'family' => 'Crete_Round',                 'category' => 'Serif',               'filename' => 'crete-round-v7-latin-ext-regular.svg'],
            ['id' => 27,      'family' => 'Pridi',                       'category' => 'Serif',               'filename' => 'pridi-v4-latin-ext-regular.svg'],
            ['id' => 28,      'family' => 'Domine',                      'category' => 'Serif',               'filename' => 'domine-v6-latin-ext-regular.svg'],
            ['id' => 29,      'family' => 'Cinzel',                      'category' => 'Serif',               'filename' => 'cinzel-v8-latin-ext-regular.svg'],
            ['id' => 30,      'family' => 'Vidaloka',                    'category' => 'Serif',               'filename' => 'vidaloka-v11-latin-regular.svg'],
            ['id' => 31,      'family' => 'Roboto',                      'category' => 'Sans-Serif',          'filename' => 'roboto-v19-latin-ext-regular.svg'],
            ['id' => 32,      'family' => 'Exo_2',                       'category' => 'Sans-Serif',          'filename' => 'exo-2-v5-latin-ext-regular.svg'],
            ['id' => 33,      'family' => 'Paytone_One',                 'category' => 'Sans-Serif',          'filename' => 'paytone-one-v11-latin-ext-regular.svg'],
            ['id' => 34,      'family' => 'Lato',                        'category' => 'Sans-Serif',          'filename' => 'lato-v15-latin-ext-regular.svg'],
            ['id' => 35,      'family' => 'Anton',                       'category' => 'Sans-Serif',          'filename' => 'anton-v10-latin-ext-regular.svg'],
            ['id' => 36,      'family' => 'Allerta_Stencil',             'category' => 'Sans-Serif',          'filename' => 'allerta-stencil-v9-latin-regular.svg'],
            ['id' => 37,      'family' => 'Montserrat',                  'category' => 'Sans-Serif',          'filename' => 'montserrat-v13-latin-ext-regular.svg'],
            ['id' => 38,      'family' => 'Fjalla_One',                  'category' => 'Sans-Serif',          'filename' => 'fjalla-one-v6-latin-ext-regular.svg'],
            ['id' => 39,      'family' => 'Russo_One',                   'category' => 'Sans-Serif',          'filename' => 'russo-one-v7-latin-ext-regular.svg'],
            ['id' => 40,      'family' => 'Oswald',                      'category' => 'Sans-Serif',          'filename' => 'oswald-v23-latin-ext-regular.svg'],
            ['id' => 41,      'family' => 'Cabin',                       'category' => 'Sans-Serif',          'filename' => 'cabin-v13-latin-ext-regular.svg'],
            ['id' => 42,      'family' => 'Orbitron',                    'category' => 'Sans-Serif',          'filename' => 'orbitron-v10-latin-regular.svg'],
            ['id' => 43,      'family' => 'Rubik_Mono_One',              'category' => 'Sans-Serif',          'filename' => 'rubik-mono-one-v7-latin-ext-regular.svg'],
            ['id' => 44,      'family' => 'Josefin_Sans',                'category' => 'Sans-Serif',          'filename' => 'josefin-sans-v13-latin-ext-regular.svg'],
            ['id' => 45,      'family' => 'Play',                        'category' => 'Sans-Serif',          'filename' => 'play-v10-latin-ext-regular.svg'],
            ['id' => 46,      'family' => 'Raleway',                     'category' => 'Sans-Serif',          'filename' => 'raleway-v13-latin-ext-regular.svg'],
            ['id' => 47,      'family' => 'Quicksand',                   'category' => 'Sans-Serif',          'filename' => 'quicksand-v9-latin-ext-regular.svg'],
            ['id' => 48,      'family' => 'Questrial',                   'category' => 'Sans-Serif',          'filename' => 'questrial-v8-latin-regular.svg'],
            ['id' => 49,      'family' => 'Poppins',                     'category' => 'Sans-Serif',          'filename' => 'poppins-v6-latin-ext-regular.svg'],
            ['id' => 50,      'family' => 'Dosis',                       'category' => 'Sans-Serif',          'filename' => 'dosis-v8-latin-ext-regular.svg'],
            ['id' => 51,      'family' => 'Acme',                        'category' => 'Sans-Serif',          'filename' => 'acme-v8-latin-regular.svg'],
            ['id' => 52,      'family' => 'Ubuntu',                      'category' => 'Sans-Serif',          'filename' => 'ubuntu-v13-latin-ext-regular.svg'],
            ['id' => 53,      'family' => 'Work_Sans',                   'category' => 'Sans-Serif',          'filename' => 'work-sans-v4-latin-ext-regular.svg'],
            ['id' => 54,      'family' => 'Asap',                        'category' => 'Sans-Serif',          'filename' => 'asap-v9-latin-ext-regular.svg'],
            ['id' => 55,      'family' => 'Muli',                        'category' => 'Sans-Serif',          'filename' => 'muli-v13-latin-ext-regular.svg'],
            ['id' => 56,      'family' => 'Nunito',                      'category' => 'Sans-Serif',          'filename' => 'nunito-v10-latin-ext-regular.svg'],
            ['id' => 57,      'family' => 'Yanone_Kaffeesatz',           'category' => 'Sans-Serif',          'filename' => 'yanone-kaffeesatz-v10-latin-ext-regular.svg'],
            ['id' => 58,      'family' => 'Stylish',                     'category' => 'Sans-Serif',          'filename' => 'stylish-v7-latin-regular.svg'],
            ['id' => 59,      'family' => 'Titillium_Web',               'category' => 'Sans-Serif',          'filename' => 'titillium-web-v7-latin-ext-regular.svg'],
            ['id' => 60,      'family' => 'Teko',                        'category' => 'Sans-Serif',          'filename' => 'teko-v8-latin-ext-regular.svg'],
            ['id' => 61,      'family' => 'Squada_One',                  'category' => 'Display',             'filename' => 'squada-one-v7-latin-regular.svg'],
            ['id' => 62,      'family' => 'Black_Ops_One',               'category' => 'Display',             'filename' => 'black-ops-one-v10-latin-ext-regular.svg'],
            ['id' => 63,      'family' => 'Baloo',                       'category' => 'Display',             'filename' => 'baloo-v4-latin-ext-regular.svg'],
            ['id' => 64,      'family' => 'Fugaz_One',                   'category' => 'Display',             'filename' => 'fugaz-one-v8-latin-regular.svg'],
            ['id' => 65,      'family' => 'Carter_One',                  'category' => 'Display',             'filename' => 'carter-one-v10-latin-regular.svg'],
            ['id' => 66,      'family' => 'Audiowide',                   'category' => 'Display',             'filename' => 'audiowide-v7-latin-ext-regular.svg'],
            ['id' => 67,      'family' => 'Monoton',                     'category' => 'Display',             'filename' => 'monoton-v8-latin-regular.svg'],
            ['id' => 68,      'family' => 'Abril_Fatface',               'category' => 'Display',             'filename' => 'abril-fatface-v10-latin-ext-regular.svg'],
            ['id' => 69,      'family' => 'Righteous',                   'category' => 'Display',             'filename' => 'righteous-v7-latin-ext-regular.svg'],
            ['id' => 70,      'family' => 'Lobster',                     'category' => 'Display',             'filename' => 'lobster-v21-latin-ext-regular.svg'],
            ['id' => 71,      'family' => 'Modak',                       'category' => 'Display',             'filename' => 'modak-v4-latin-ext-regular.svg'],
            ['id' => 72,      'family' => 'Pirata_One',                  'category' => 'Display',             'filename' => 'pirata-one-v7-latin-ext-regular.svg'],
            ['id' => 73,      'family' => 'Uncial_Antiqua',              'category' => 'Display',             'filename' => 'uncial-antiqua-v6-latin-regular.svg'],
            ['id' => 74,      'family' => 'Cherry_Swash',                'category' => 'Display',             'filename' => 'cherry-swash-v7-latin-ext-regular.svg'],
            ['id' => 75,      'family' => 'UnifrakturMaguntia',          'category' => 'Display',             'filename' => 'unifrakturcook-v10-latin-700.svg'],
            ['id' => 76,      'family' => 'Mystery_Quest',               'category' => 'Display',             'filename' => 'mystery-quest-v6-latin-ext-regular.svg'],
            ['id' => 77,      'family' => 'Emilys_Candy',                'category' => 'Display',             'filename' => 'emilys-candy-v6-latin-ext-regular.svg'],
            ['id' => 78,      'family' => 'Titan_One',                   'category' => 'Display',             'filename' => 'titan-one-v6-latin-ext-regular.svg'],
            ['id' => 79,      'family' => 'Bungee',                      'category' => 'Display',             'filename' => 'bungee-v4-latin-ext-regular.svg'],
            ['id' => 80,      'family' => 'Shrikhand',                   'category' => 'Display',             'filename' => 'shrikhand-v4-latin-ext-regular.svg'],
            ['id' => 81,      'family' => 'Kenia',                       'category' => 'Display',             'filename' => 'kenia-v10-latin-regular.svg'],
            ['id' => 82,      'family' => 'Flavors',                     'category' => 'Display',             'filename' => 'flavors-v7-latin-regular.svg'],
            ['id' => 83,      'family' => 'Henny_Penny',                 'category' => 'Display',             'filename' => 'henny-penny-v6-latin-regular.svg'],
            ['id' => 84,      'family' => 'Iceberg',                     'category' => 'Display',             'filename' => 'iceberg-v6-latin-regular.svg'],
            ['id' => 85,      'family' => 'Plaster',                     'category' => 'Display',             'filename' => 'plaster-v10-latin-regular.svg'],
            ['id' => 86,      'family' => 'Niconne',                     'category' => 'Handwriting',         'filename' => 'niconne-v8-latin-ext-regular.svg'],
            ['id' => 87,      'family' => 'Pinyon_Script',               'category' => 'Handwriting',         'filename' => 'pinyon-script-v8-latin-regular.svg'],
            ['id' => 88,      'family' => 'Alex_Brush',                  'category' => 'Handwriting',         'filename' => 'alex-brush-v10-latin-ext-regular.svg'],
            ['id' => 89,      'family' => 'Damion',                      'category' => 'Handwriting',         'filename' => 'damion-v8-latin-regular.svg'],
            ['id' => 90,      'family' => 'Sacramento',                  'category' => 'Handwriting',         'filename' => 'sacramento-v6-latin-ext-regular.svg'],
            ['id' => 91,      'family' => 'Cookie',                      'category' => 'Handwriting',         'filename' => 'cookie-v10-latin-regular.svg'],
            ['id' => 92,      'family' => 'Great_Vibes',                 'category' => 'Handwriting',         'filename' => 'great-vibes-v6-latin-ext-regular.svg'],
            ['id' => 93,      'family' => 'Satisfy',                     'category' => 'Handwriting',         'filename' => 'satisfy-v9-latin-regular.svg'],
            ['id' => 94,      'family' => 'Amatic_SC',                   'category' => 'Handwriting',         'filename' => 'amatic-sc-v12-latin-ext-regular.svg'],
            ['id' => 95,      'family' => 'Pacifico',                    'category' => 'Handwriting',         'filename' => 'pacifico-v14-latin-ext-regular.svg'],
            ['id' => 96,      'family' => 'Engagement',                  'category' => 'Handwriting',         'filename' => 'engagement-v8-latin-regular.svg'],
            ['id' => 97,      'family' => 'Delius_Swash_Caps',           'category' => 'Handwriting',         'filename' => 'delius-swash-caps-v10-latin-regular.svg'],
            ['id' => 98,      'family' => 'Vibur',                       'category' => 'Handwriting',         'filename' => 'vibur-v9-latin-regular.svg'],
            ['id' => 99,      'family' => 'Sofia',                       'category' => 'Handwriting',         'filename' => 'sofia-v7-latin-regular.svg'],
            ['id' => 100,     'family' => 'Rouge_Script',                'category' => 'Handwriting',         'filename' => 'rouge-script-v7-latin-regular.svg'],
            ['id' => 101,     'family' => 'Mr_De_Haviland',              'category' => 'Handwriting',         'filename' => 'mr-de-haviland-v7-latin-ext-regular.svg'],
            ['id' => 102,     'family' => 'Norican',                     'category' => 'Handwriting',         'filename' => 'norican-v7-latin-ext-regular.svg'],
            ['id' => 103,     'family' => 'Grand_Hotel',                 'category' => 'Handwriting',         'filename' => 'grand-hotel-v6-latin-ext-regular.svg'],
            ['id' => 104,     'family' => 'Rochester',                   'category' => 'Handwriting',         'filename' => 'rochester-v9-latin-regular.svg'],
            ['id' => 105,     'family' => 'Berkshire_Swash',             'category' => 'Handwriting',         'filename' => 'berkshire-swash-v7-latin-ext-regular.svg'],
            ['id' => 106,     'family' => 'Romanesco',                   'category' => 'Handwriting',         'filename' => 'romanesco-v7-latin-ext-regular.svg'],
            ['id' => 107,     'family' => 'Miss_Fajardose',              'category' => 'Handwriting',         'filename' => 'miss-fajardose-v8-latin-ext-regular.svg'],
            ['id' => 108,     'family' => 'Monsieur_La_Doulaise',        'category' => 'Handwriting',         'filename' => 'monsieur-la-doulaise-v7-latin-ext-regular.svg'],
            ['id' => 109,     'family' => 'Lovers_Quarrel',              'category' => 'Handwriting',         'filename' => 'lovers-quarrel-v6-latin-ext-regular.svg'],
        ];
        
        DB::table('fonts')->insert($fonts);
    }
}
